import type { Metadata } from "next";
import { Geist_Mono, Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/presentation/context/QueryProvider";
import DIConfig from "@/ioc/DIConfig";
import { Toaster } from "sonner";
import Navbar from "@/presentation/components/Navbar";

const serif = Playfair_Display({
  variable: "--font-serif",
  subsets: ["latin"],
});

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        {process.env.NODE_ENV === "development" && (
          <script
            async
            crossOrigin="anonymous"
            src="//unpkg.com/react-scan/dist/auto.global.js"
          />
        )}
      </head>
      <body
        className={`${sans.variable} ${serif.variable} ${geistMono.variable} bg-background grid min-h-dvh auto-rows-auto antialiased`}
      >
        <QueryProvider>
          <DIConfig>
            <Navbar />
            {children}
          </DIConfig>
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
